name: CI Pipeline

on:
  push:

jobs:
  project-testing:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_URL: ${{ secrets.DAGSHUB_URL }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      REPO_OWNER: ${{ secrets.REPO_OWNER }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION_NAME }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DVC pipeline
        run: dvc repro

      - name: Run model tests
        run: python -m unittest tests/test_model.py

      - name: Promote model to Production
        if: success()
        run: python scripts/promote_model.py

      - name: Run Flask tests
        if: success()
        run: python -m unittest tests/test_flask_app.py

      - name: Configure AWS Credentials
        if: success()
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Login to Amazon ECR
        if: success()
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login \
            --username AWS \
            --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        if: success()
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      - name: Tag Docker image
        if: success()
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        if: success()
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Setup kubectl
        if: success()
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Update kubeconfig
        if: success()
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name flask-app-cluster

      - name: Create Kubernetes Secret
        if: success()
        run: |
          kubectl create secret generic capstone-secret \
            --from-literal=CAPSTONE_TEST=$CAPSTONE_TEST \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to EKS
        if: success()
        run: |
          kubectl apply -f deployment.yaml